# crypto.toml - Configuration for WeatherChecker or related crypto settings

[weather]
# Default coordinates (latitude, longitude, elevation)
latitude = 42.96166385219277
longitude = -83.06824754518021
elevation = 850
station = 'KD95'
interval_seconds = 3600  # Interval between board commands in seconds (default: 1 hour)

# Add other configuration options as needed
